#服务端口
server:
  port: 8088
  tomcat:
    max-threads: 200
    uri-encoding: UTF-8

#服务注册中心
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 30
    instance-id: ${spring.application.name}:${server.port}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/  
    
##数据库连接信息
spring:
  cloud:
    config:
      uri: http://localhost:8888
      profile: dev
      label: master #当 ConfigServer 的后端存储的是 Git 的时候，默认就是 master
      
  datasource:
    url: jdbc:mysql://192.168.4.30:3306/test?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: doyd1913
    driver-class-name: com.mysql.jdbc.Driver
    platform: mysql
###################以下为druid增加的配置###########################
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 5  # 初始化大小，最小，最大
    minIdle: 5
    maxActive: 20
    maxWait: 60000  # 配置获取连接等待超时的时间
    timeBetweenEvictionRunsMillis: 60000  # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    minEvictableIdleTimeMillis: 300000    # 配置一个连接在池中最小生存的时间，单位是毫秒
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true  # 打开PSCache，并且指定每个连接上PSCache的大小
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,log4j      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000 # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
# 合并多个DruidDataSource的监控数据
#spring.datasource.useGlobalDataSourceStat=true
###############以上为配置druid添加的配置########################################
  
###############Redis配置########################################
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    publisher-confirms: true
    virtual-host: /
    
  redis:
    database: 1
    password: doyd1913
    host: localhost
    lettuce:
      pool:
        max-active: 100 # 连接池最大连接数（使用负值表示没有限制）
        max-idle: 100   # 连接池中的最大空闲连接
        min-idle: 50    # 连接池中的最小空闲连接
        max-wait: 6000  # 连接池最大阻塞等待时间（使用负值表示没有限制）
    timeout: 1000

#微信相关参数
wechat:
  mpAppId:  wx47683545fa4b7115
  mpAppSecret: 831d9f44acab508e091e3f1bcf0e7cbd 